# 2. NumpPy 배열

* NumPy에는 ndarray라는 데이터 타입의 배열이 생성된다.
* ndarray는 같은 타입의 데이터만 저장할 수 있다.
* Python의 list보다 계산 속도가 빠르다.

In [1]:
# import 하기
import numpy as np

## 2-1. np.array() 함수로 생성하기
### 1차원 배열 생성하기

In [8]:
# 1차원 배열
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [5]:
#type 확인
type(arr)

numpy.ndarray

In [10]:
# array()에는 반드시 data가 1개 들어가야 한다!!
np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [11]:
# data type
arr.dtype

dtype('int32')

In [15]:
# overflow 테스트
arr = np.array([2147483648, 2, 3, 4], dtype=np.int64)
arr

array([2147483648,          2,          3,          4], dtype=int64)

In [17]:
arr = np.array([1, 2, 3, 4], dtype=float) #np.float64
arr

array([1., 2., 3., 4.])

In [18]:
arr.dtype

dtype('float64')

In [19]:
# shape : 각 차원의 배열의 size (모양)
arr.shape

(4,)

In [20]:
# size : 배열의 전체 element 수
arr.size

4

In [21]:
# ndim : 차원의 수
arr.ndim

1

In [22]:
arr = np.array([1, 2, 3, 3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [23]:
arr = np.array([1, 2, 3, 3.14], dtype=int)
arr

array([1, 2, 3, 3])

In [29]:
# > : big-endian, < : Little-endian
arr = np.array([1, 3.14, '1234'])
arr

array(['1', '3.14', '1234'], dtype='<U32')

In [31]:
# 이미 있는 배열을 타입이 다른 다른 배열로 생성하기
new_arr = arr.astype(float)
new_arr

array([1.000e+00, 3.140e+00, 1.234e+03])

In [32]:
arr.dtype, new_arr.dtype

(dtype('<U32'), dtype('float64'))

In [3]:
arr = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])
new_arr = np.array([arr, arr2])
new_arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### 2차원 배열 생성하기

In [4]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6 ,7, 8],
                 [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('int32'), (3, 4), 12, 2)

In [6]:
new_arr = arr2.astype(int)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2-2. np.arrange() 함수로 생성하기

In [8]:
# 파이썬의 range
for i in range(0, 10, 2): #0, 9
    print(i)

0
2
4
6
8


### 1차원 배열 생성하기

In [11]:
# 1~10
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

### 2차원 배열 생성하기

In [31]:
# 0~11
arr = np.arange(0, 12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
arr2 = arr.reshape((3, 4))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
arr, arr2

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [22]:
arr2 = arr.reshape((3, 5))
arr2

ValueError: cannot reshape array of size 12 into shape (3,5)

In [32]:
# 원본 배열의 shape를 변경하고자 할 경우
arr.shape = (3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수

In [26]:
# 1차원 배열
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [27]:
# 2차원 배열
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2-4. np.ones() 함수

In [29]:
# 1차원 배열
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [30]:
# 2차원 배열
arr2 = np.ones((3, 4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 2-5. np.linspace() 함수

In [34]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
arr = np.linspace(0, 10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [36]:
arr.shape

(50,)

In [38]:
arr2 = arr.reshape((10, 5))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653],
       [ 1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286],
       [ 3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918],
       [ 5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551],
       [ 7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184],
       [ 9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

## 2-6. np.full() 함수

In [39]:
# 특정 값으로 배열을 생성할 경우
arr = np.full(4, 10)
arr

array([10, 10, 10, 10])

In [40]:
arr2 = np.full((3, 4), 10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

## 2-7. np.eye() 함수

In [42]:
# 단위 행렬 ( 항등 행렬 )
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2-8. np.random을 이용

In [1]:
import numpy as np

In [2]:
arr = np.random.rand(4)
arr

array([0.65650172, 0.75774742, 0.87461519, 0.78281184])

In [3]:
arr2 = np.random.rand(3, 4)
arr2

array([[0.38062398, 0.758262  , 0.30798786, 0.47992107],
       [0.17221716, 0.44424108, 0.55168236, 0.49820074],
       [0.16440741, 0.48255125, 0.24189471, 0.94632387]])

In [5]:
arr = np.random.randint(5, size=10)
arr

array([2, 4, 1, 0, 0, 2, 0, 4, 4, 3])

In [6]:
arr2 = np.random.randint(1, 5 ,size=(3, 4))
arr2

array([[3, 2, 3, 2],
       [2, 4, 4, 4],
       [4, 3, 1, 4]])

In [27]:
# 일정한 랜덤값을 만드려면?
np.random.seed(123)
np.random.rand(3, 4)

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971]])

## 2-9. Numpy 배열 Save & Load

In [30]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [31]:
np.save('my_arr', arr)

In [32]:
new_arr = np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])