# 3. 연산

## 3-1. 산술연산

### 1차원 배열

In [1]:
import numpy as np

In [4]:
a = np.arange(1, 5) #1~4
b = np.arange(5, 9) #5~8
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [3]:
a.shape, b.shape

((4,), (4,))

In [4]:
# shape이 같아야 함
a + b

array([ 6,  8, 10, 12])

In [5]:
a - b

array([-4, -4, -4, -4])

In [6]:
a * b

array([ 5, 12, 21, 32])

In [7]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### 2차원 배열

In [5]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b = np.arange(7, 13).reshape(2, 3)
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [12]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [13]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [14]:
# 단순 곱셈  (이렇게는 안쓰임)
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [15]:
a / b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

### 행렬의 곱셈 (dot product)

In [9]:
### 중요
b = np.arange(1, 7).reshape(3, 2)
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [10]:
np.dot(a, b)

array([[22, 28],
       [49, 64]])

In [11]:
a.dot(b)

array([[22, 28],
       [49, 64]])

In [13]:
# 비교
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a < 4

array([[ True,  True,  True],
       [False, False, False]])

### 배열과 숫자(Scalar)와의 연산

In [16]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [17]:
a + 3

array([4, 5, 6])

In [18]:
a - 3

array([-2, -1,  0])

In [19]:
a * 3

array([3, 6, 9])

In [20]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

### 1차원 배열

In [22]:
a = np.array([1, 2 ,3 ,4 ,5])
a

array([1, 2, 3, 4, 5])

In [23]:
# max값 찾기
np.max(a)

5

In [24]:
a.max()

5

In [25]:
# min값 찾기
np.min(a)

1

In [26]:
a.min()

1

In [27]:
# 배열요소의 합 구하기
np.sum(a)

15

In [29]:
# 평균구하기 (average 비교)
np.mean(a)

3.0

In [32]:
# 이상치(Outlier)가 있는 경우에는 mean값이 배열을 대표할 수 없음
a = np.array([1, 100, 2, 4, 3])
np.mean(a)

22.0

In [33]:
# 중앙값(중위값)
np.median(a)

3.0

In [34]:
# 짝수인 경우
a = np.array([1, 100, 2, 4])
np.median(a)

3.0

In [35]:
# std : 표준편차 (standard deviation)
np.std(a)

42.30469832063574

### 2차원 배열

In [38]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.max(a)

6

In [40]:
np.min(a)

1

In [41]:
np.max(a, axis=0)

array([4, 5, 6])

In [43]:
np.max(a, axis=1)

array([3, 6])

In [44]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.sum(a)

21

In [46]:
np.sum(a, axis=0)

array([5, 7, 9])

In [47]:
np.sum(a, axis=1)

array([ 6, 15])

In [48]:
# cumsum
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [49]:
np.cumsum(a, axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [51]:
np.cumsum(a, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [17]:
# corrcoef (상관계수)
# 두 변수 사이의 연관성을 나타내는 수치
# 키와 몸무게의 상관관계와 몸무게의 상관관계
h = [160, 165, 170, 180]
w = [47, 55, 70 ,85]
np.corrcoef(h, w)

array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

In [18]:
ha = np.mean(h)
wa = np.mean(w)
ha, wa

(168.75, 64.25)

In [19]:
a = np.sqrt(np.sum((h - ha) ** 2))
a

14.79019945774904

In [20]:
b = np.sqrt(np.sum((w - wa) ** 2))
b

29.098969053902923

In [21]:
c = np.sum((h - ha) * (w - wa))
c

426.25

In [22]:
r = c / (a * b)
r

0.990404850180661