# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [1]:
import numpy as np

In [2]:
# 1차원 배열
arr = np.arange(1, 11) # 1~10까지
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1], arr[4], arr[-1]

(2, 5, 10)

In [4]:
# 2차원 배열
arr2 = np.arange(1, 13).reshape(3, 4)   # 1~12까지 3*4
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr2[0, 1], arr2[1, 2], arr2[-1, -1]

(2, 7, 12)

In [13]:
# 다차원 indexing
arr2[0, 1], arr2[1, 2], arr2[-1, -1]

(2, 7, 12)

## 5-2. 슬라이싱

In [14]:
# 1차원 배열
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# 슬라이싱 [start:end:step]
arr[2:6]

array([3, 4, 5, 6])

In [17]:
# 3~끝까지
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# 처음~6까지
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [21]:
# 처음~끝까지
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# 슬라이싱한 후 값을 변경하면 원본 배열에 영향을 미칠까?
new_arr = arr[2:6]
new_arr

array([3, 4, 5, 6])

In [25]:
new_arr[0]=100
new_arr

array([100,   4,   5,   6])

In [26]:
arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [27]:
copy_arr = np.copy(arr)
copy_arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [28]:
arr[::2]

array([  1, 100,   5,   7,   9])

In [29]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
# 첫번째 행을 가져오기
arr2[0, :]

array([1, 2, 3, 4])

In [35]:
# 세번째 열을 가져오기
arr2[:, 2]

array([ 3,  7, 11])

In [37]:
# 첫번째, 두번째 행을 가져오기
arr2[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
# 두번째, 세번째 열을 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [42]:
arr2[:2, 1:-1]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [6]:
# 1차원
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# [3, 6, 8]로 된 1차원 배열 만들기
np.array([arr[2], arr[5], arr[7]])

array([3, 6, 8])

In [7]:
# Fancy 인덱싱
# 인덱스로 배열 만들기
arr[[2, 5, 7]]

array([3, 6, 8])

In [9]:
# 2차원 배열
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr2[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [13]:
# 슬라이싱
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [14]:
# Fancy 인덱싱
arr2[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [16]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [19]:
cond = [True, True, False, False, True]

In [21]:
# Boolean 인덱싱
arr[cond]

array([0, 1, 4])

In [22]:
arr > 2

array([False, False, False,  True,  True])

In [23]:
arr[arr > 2]

array([3, 4])

In [24]:
# 짝수
arr[arr % 2 == 0]

array([0, 2, 4])

In [35]:
# 1보다 작거나 3보다 큰 수 (0, 4)
(arr < 1) | (arr > 3)

array([ True, False, False, False,  True])

In [36]:
arr[(arr < 1) | (arr > 3)]

array([0, 4])

In [37]:
# 2이상 3이하인 수 (2, 3)
(arr >= 2) & (arr <= 3)

array([False, False,  True,  True, False])

In [38]:
arr[(arr >= 2) & (arr <= 3)]

array([2, 3])