# 실전 적용!!!

In [1]:
# numpy import하기
import numpy as np

## 1. NumPy 배열 생성

In [4]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기 #변수 명은 자유!
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
arr.dtype, arr.shape, arr.size, arr.ndim

(dtype('int32'), (5,), 5, 1)

In [7]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [9]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr3 = np.arange(1, 6)
arr3

array([1, 2, 3, 4, 5])

In [10]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr4 = np.arange(10, 90, 10).reshape(2, 4)
arr4

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 2. 산술연산

In [11]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기
arr1 = np.arange(1, 6)
arr2 = np.arange(6, 11)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [12]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기
arr1 + arr2, arr1 - arr2, arr1 * arr2 , arr1 / arr2

(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]))

In [13]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기
arr1 = np.arange(1, 11).reshape(2, 5)
arr2 = np.arange(11, 21).reshape(2, 5)
arr1, arr2

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [14]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
arr1 + arr2, arr1 - arr2, arr1 * arr2, arr1 / arr2

(array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]),
 array([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]]),
 array([[ 11,  24,  39,  56,  75],
        [ 96, 119, 144, 171, 200]]),
 array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
        [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]]))

In [16]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
arr2 = arr2.reshape(5, 2)
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [17]:
# 행렬곱셈(dot product) 연산하기
np.dot(arr1, arr2)

array([[245, 260],
       [620, 660]])

## 3. Aggregation 함수

In [18]:
# 1~10까지 이루어진 1차원 배열 생성하기
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# 최대값, 최소값 출력하기
np.max(arr), np.min(arr)

(10, 1)

In [22]:
# 배열요소의 합, 평균값 출력하기
np.sum(arr), np.mean(arr)

(55, 5.5)

In [24]:
# 중앙값(중위값), 표준편차 출력하기
np.median(arr), np.std(arr)

(5.5, 2.8722813232690143)

In [26]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
arr = np.arange(1, 21).reshape(4, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
# 각 행의 max값, min값 출력하기
np.max(arr, axis=1), np.min(arr, axis=1)

(array([ 5, 10, 15, 20]), array([ 1,  6, 11, 16]))

In [29]:
# 각 열의 max값, min값 출력하기
np.max(arr, axis=0), np.min(arr, axis=0)

(array([16, 17, 18, 19, 20]), array([1, 2, 3, 4, 5]))

In [30]:
# 각 행의 sum값 출력하기
np.sum(arr, axis=1)

array([15, 40, 65, 90])

In [31]:
# 각 열의 sum값 출력하기
np.sum(arr, axis=0)

array([34, 38, 42, 46, 50])

## 4. 인덱싱과 슬라이싱

In [32]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
# 위 배열에서 7을 인덱싱하기
arr[1, 2]

7

In [52]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
arr[-1, -1]

14

In [47]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
arr[1, 1:3]

array([6, 7])

In [55]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
arr[1:, 2]

array([ 7, 12])

In [46]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
arr[:2, 3:]

array([[3, 4],
       [8, 9]])

In [49]:
# 위 배열에서 3의 배수 찾기
arr[arr % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [50]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
arr[arr % 4 ==1]

array([ 1,  5,  9, 13])

In [51]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
arr[(arr % 3 == 0) & (arr % 4 == 1)]

array([9])